version: "3"
services:
  test-suite:
    image: anubhavgupta11/selenium-docker
    environment:
      - BROWSER
      - HUB_HOST=hub
      - THREAD_COUNT=2
      - TEST_SUITE
    volumes:
      - ./Docker-Output/${TEST_SUITE}/${BROWSER}:/home/Selenium-Docker/test-output/ExtentReport/