version: "3"
services:
  test-suite:
    image: anubhavgupta11/selenium-docker
    environment:
      - BROWSER
      - HUB_HOST=hub
      - THREAD_COUNT=5
      - TEST_SUITE
    volumes:
      - ./Docker-Output:/home/Selenium-Docker/test-output/ExtentReport/